import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import Nav from './nav';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Info 100 - ApisCondusef",
  description: "Generated by Info 100",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
     
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      
        <Nav/>
        {children}
      </body>
    </html>
  );
}
